Update git workflow

diff --git a/.github/workflows/version-check.yml b/.github/workflows/version-check.yml
--- a/.github/workflows/version-check.yml
+++ b/.github/workflows/version-check.yml
@@ -1,32 +1,35 @@
 name: PackageVersionUpdated
 on:
   pull_request:
+    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
+    branches:
+      - develop
     paths:
       - 'love/package.json'
 jobs:
-  version-check:
+  build:
+    name: Check Actions
     runs-on: ubuntu-latest
-
     steps:
-    - name: Check out code
-      uses: actions/checkout@v2
+      - name: Check out code
+        uses: actions/checkout@v1
 
-    - name: Check version change in package.json
-      run: |
-        # Checkout the target branch
-        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
-        git checkout ${{ github.base_ref }}
+      - name: Check version change in package.json
+        run: |
+          # Checkout the target branch
+          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
+          git checkout ${{ github.base_ref }}
 
-        # Get the version before the changes
-        BASE_VERSION=$(cat package.json | jq -r .version)
+          # Get the version before the changes
+          BASE_VERSION=$(cat package.json | jq -r .version)
 
-        # Checkout the PR branch
-        git checkout -
+          # Checkout the PR branch
+          git checkout -
 
-        # Get the version after the changes
-        HEAD_VERSION=$(cat package.json | jq -r .version)
+          # Get the version after the changes
+          HEAD_VERSION=$(cat package.json | jq -r .version)
 
-        if [ "$BASE_VERSION" == "$HEAD_VERSION" ]; then
-          echo "Error: Version in package.json was not updated!"
-          exit 1
-        fi
+          if [ "$BASE_VERSION" == "$HEAD_VERSION" ]; then
+            echo "Error: Version in package.json was not updated!"
+            exit 1
+          fi
